from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

s=re.sub(r'<!-- pages-publish:[^>]+-->', '<!-- pages-publish: assistant-v01-2026-09-05 -->', s, count=1)

old_tile='<div class="tile"><h3>الإجراءات والمتابعة</h3><button class="btn" onclick="openActions()">فتح</button></div>'
new_tile=old_tile+'<div class="tile"><h3>مساعد ركيزة ✦</h3><button class="btn gold" onclick="openAssistant()">اسأل ركيزة</button></div>'
assert old_tile in s, 'actions tile not found'
s=s.replace(old_tile,new_tile,1)

assistant_section='''<section id="assistant" class="view"><div class="top"><div><div class="brand">مساعد ركيزة ✦</div><div class="sub">نسخة تجريبية — اسأل عن بيانات التشغيل واطلب تقارير</div></div><button class="btn ghost" onclick="home()">الرئيسية</button></div><div class="grid"><div class="card wide"><div class="title">اسأل ركيزة</div><div class="notice">النسخة الأولى تقرأ بيانات ركيزة فقط ولا تعدّل أو تغلق أي سجل. جرّب سؤالًا طبيعيًا أو اختر أحد الأمثلة.</div><div id="assistantSuggestions" class="actions" style="justify-content:flex-start;flex-wrap:wrap"><button class="mini" onclick="askAssistantQuick('وش أكثر مشكلة حصلت معنا؟')">أكثر مشكلة تكررت</button><button class="mini" onclick="askAssistantQuick('وش أكثر منتج نقص عندي؟')">أكثر نقص متكرر</button><button class="mini" onclick="askAssistantQuick('وش الإجراءات المفتوحة؟')">الإجراءات المفتوحة</button><button class="mini" onclick="askAssistantQuick('صدر لي مبيعات الشهر الماضي مع التارقت Excel')">مبيعات الشهر الماضي Excel</button></div><div id="assistantChat" style="display:flex;flex-direction:column;gap:10px;margin-top:14px"></div><div class="fields" style="margin-top:14px;grid-template-columns:1fr auto"><div class="field"><label>اكتب سؤالك</label><input id="assistantInput" placeholder="مثال: صدر لي مبيعات أغسطس مع التارقت اكسل" onkeydown="if(event.key==='Enter'){event.preventDefault();askRakizaAssistant()}"></div><div class="field"><label>&nbsp;</label><button class="btn gold" onclick="askRakizaAssistant()">إرسال</button></div></div></div></div></section>'''
anchor='<section id="actions" class="view">'
assert anchor in s, 'actions section anchor not found'
s=s.replace(anchor,assistant_section+anchor,1)

assistant_js=r'''let assistantReady=false,assistantLastSales=null;
function assistantNorm(v){return String(v||'').trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي')}
function assistantEscText(v){return esc(String(v??''))}
function assistantAdd(role,html){let c=$('assistantChat');if(!c)return;let mine=role==='user';c.insertAdjacentHTML('beforeend',`<div style="display:flex;justify-content:${mine?'flex-start':'flex-end'}"><div class="task" style="max-width:86%;margin:0;background:${mine?'#eef3f8':'#fff'};border-color:${mine?'#d6e0ea':'#e3e7ec'}">${html}</div></div>`);c.scrollTop=c.scrollHeight;c.lastElementChild?.scrollIntoView({behavior:'smooth',block:'nearest'})}
function assistantInit(){if(assistantReady)return;assistantReady=true;assistantAdd('assistant','<b>أهلًا، أنا مساعد ركيزة التجريبي.</b><div class="mut" style="margin-top:6px">اسألني عن المبيعات، النواقص، المشكلات المسجلة أو الإجراءات المفتوحة. وأقدر أجهز مبيعات شهر في ملف Excel.</div>')}
function openAssistant(){show('assistant');assistantInit();setTimeout(()=>$('assistantInput')?.focus(),50)}
function askAssistantQuick(q){$('assistantInput').value=q;askRakizaAssistant()}
function assistantMonth(text){let t=assistantNorm(text),d=new Date((app.calendarDate||app.date||new Date().toISOString().slice(0,10))+'T00:00:00');let y=d.getFullYear(),m=d.getMonth()+1;let names={يناير:1,فبراير:2,مارس:3,ابريل:4,مايو:5,يونيو:6,يوليو:7,اغسطس:8,سبتمبر:9,اكتوبر:10,نوفمبر:11,ديسمبر:12};for(let [k,v] of Object.entries(names))if(t.includes(k))m=v;let yr=t.match(/\b(20\d{2})\b/);if(yr)y=Number(yr[1]);let ym=t.match(/(20\d{2})\s*[-\/]\s*(1[0-2]|0?[1-9])/);if(ym){y=Number(ym[1]);m=Number(ym[2])}let my=t.match(/(?:^|\s)(1[0-2]|0?[1-9])\s*[-\/]\s*(20\d{2})/);if(my){m=Number(my[1]);y=Number(my[2])}if(t.includes('الشهر الماضي')||t.includes('الشهر السابق')){let z=new Date(y,m-2,1);y=z.getFullYear();m=z.getMonth()+1}if(t.includes('هذا الشهر')||t.includes('الشهر الحالي')){y=d.getFullYear();m=d.getMonth()+1}return`${y}-${String(m).padStart(2,'0')}`}
function assistantSales(month){let rows=(app.recent||[]).filter(x=>String(x.work_date||'').startsWith(month)).sort((a,b)=>String(a.work_date).localeCompare(String(b.work_date))),latest=[...rows].reverse().find(x=>x.month_sales_after_close!=null),sales=latest?Number(latest.month_sales_after_close||0):rows.reduce((n,x)=>n+Number(x.daily_sales||0),0),target=0;for(let x of rows){let v=Number(x.monthly_target_snapshot||0);if(v){target=v;break}}let current=(app.calendarDate||app.date||'').slice(0,7);if(!target&&month===current)target=Number(app.monthlyTarget||0);let achievement=target?sales/target*100:0,gap=target?sales-target:null;return{month,rows,sales,target,achievement,gap}}
async function assistantShortages(){if(!Array.isArray(shortagesData)||!shortagesData.length)try{shortagesData=await api('shortages')}catch(e){}let map=new Map();for(let x of shortagesData||[]){let sec=x.sections?.name||'—',key=sec+'|'+x.size,z=map.get(key)||{section:sec,item:x.size,count:0,requested:0,lost:0,last:x.first_detected_date};z.count++;z.requested+=Number(x.requested_qty||0);z.lost+=Number(x.lost_opportunities||0);if(String(x.first_detected_date)>String(z.last))z.last=x.first_detected_date;map.set(key,z)}return[...map.values()].sort((a,b)=>b.count-a.count||b.requested-a.requested).slice(0,5)}
function assistantProblems(){let rows=(app.actions||[]).filter(x=>x.action_type!=='نواقص'),map=new Map();for(let x of rows){let key=String(x.action_type||'غير مصنف').trim(),z=map.get(key)||{type:key,count:0,open:0};z.count++;if(x.action_status!=='مغلق')z.open++;map.set(key,z)}return[...map.values()].sort((a,b)=>b.count-a.count).slice(0,5)}
function assistantOpenActions(){return(app.actions||[]).filter(x=>x.action_status!=='مغلق').sort((a,b)=>String(a.request_date).localeCompare(String(b.request_date)))}
async function assistantExportSales(data){if(typeof ExcelJS==='undefined')throw Error('محرك Excel غير متاح حاليًا');let wb=new ExcelJS.Workbook();wb.creator='Rakiza Assistant';let s=wb.addWorksheet('Summary');s.addRow(['تقرير مبيعات ركيزة']);s.addRow(['الشهر',data.month]);s.addRow(['المستهدف',data.target||'غير مسجل']);s.addRow(['المبيعات',data.sales]);s.addRow(['نسبة التحقيق',data.target?data.achievement/100:'']);s.addRow(['الفجوة',data.gap??'']);s.getColumn(1).width=24;s.getColumn(2).width=20;s.getRow(1).font={bold:true,size:14};s.getCell('B5').numFmt='0.0%';let d=wb.addWorksheet('Daily Sales');d.addRow(['التاريخ','اليوم','مستهدف اليوم','مبيعات اليوم','تحقيق اليوم','الجاهزية','تواجد الفريق']);for(let x of data.rows)d.addRow([x.work_date,x.day_name||'',Number(x.daily_target||0),Number(x.daily_sales||0),Number(x.daily_achievement||0)/100,x.operational_readiness??'',x.attendance_adequacy??'']);d.columns=[{width:14},{width:14},{width:16},{width:16},{width:14},{width:14},{width:14}];d.getRow(1).font={bold:true};d.getColumn(5).numFmt='0.0%';let buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`مبيعات ركيزة - ${data.month}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
async function assistantExportLastSales(){try{if(!assistantLastSales)throw Error('اطلب تقرير مبيعات أولًا');await assistantExportSales(assistantLastSales);assistantAdd('assistant','تم تجهيز ملف Excel وتحميله ✅')}catch(e){assistantAdd('assistant',`<span class="re">${assistantEscText(e.message)}</span>`)}}
async function askRakizaAssistant(){assistantInit();let inp=$('assistantInput'),q=inp.value.trim();if(!q)return;inp.value='';assistantAdd('user',assistantEscText(q));let t=assistantNorm(q);try{if(t.includes('مبيعات')||t.includes('تارقت')||t.includes('مستهدف')||(t.includes('تقرير')&&t.includes('شهر'))){let month=assistantMonth(q),data=assistantSales(month);assistantLastSales=data;if(!data.rows.length){assistantAdd('assistant',`ما عندي بيانات مبيعات للشهر <b>${month}</b> ضمن السجل المتاح حاليًا. النسخة الأولى تقرأ آخر أيام التشغيل المحملة في ركيزة.`);return}let gap=data.gap==null?'—':`${data.gap>=0?'+':''}${data.gap.toLocaleString('en-US')} ريال`,html=`<b>مبيعات ${month}</b><div style="margin-top:8px">المبيعات: <b>${data.sales.toLocaleString('en-US')} ريال</b><br>المستهدف: <b>${data.target?data.target.toLocaleString('en-US')+' ريال':'غير مسجل'}</b><br>نسبة التحقيق: <b>${data.target?data.achievement.toFixed(1)+'%':'—'}</b><br>الفجوة: <b>${gap}</b></div><div style="margin-top:10px"><button class="mini" onclick="assistantExportLastSales()">تصدير Excel</button></div>`;assistantAdd('assistant',html);if(t.includes('صدر')||t.includes('اكسل')||t.includes('excel'))await assistantExportLastSales();return}
if(t.includes('نقص')||t.includes('نواقص')||(t.includes('منتج')&&t.includes('اكثر'))){let top=await assistantShortages();if(!top.length){assistantAdd('assistant','لا توجد بيانات نواقص كافية حتى الآن.');return}let first=top[0],list=top.map((x,i)=>`${i+1}. ${assistantEscText(x.item)} — ${assistantEscText(x.section)} <span class="mut">(${x.count} مرات، طلب ${x.requested})</span>`).join('<br>');assistantAdd('assistant',`<b>الأكثر تكرارًا:</b> ${assistantEscText(first.item)} ضمن ${assistantEscText(first.section)}، تكرر <b>${first.count}</b> مرة بإجمالي طلب <b>${first.requested}</b>${first.lost?` وفرص ضائعة ${first.lost}`:''}.<div class="mut" style="margin-top:9px">أعلى الأصناف:</div><div style="margin-top:5px">${list}</div>`);return}
if(t.includes('مشكله')||t.includes('مشاكل')){let top=assistantProblems();if(!top.length){assistantAdd('assistant','لا توجد مشكلات مسجلة بشكل كافٍ في سجل الإجراءات حتى الآن.');return}let first=top[0],list=top.map((x,i)=>`${i+1}. ${assistantEscText(x.type)} — ${x.count} مرات${x.open?` (${x.open} مفتوحة)`:''}`).join('<br>');assistantAdd('assistant',`بحسب <b>سجل الإجراءات</b>، أكثر نوع مشكلة تكرر هو <b>${assistantEscText(first.type)}</b> بعدد ${first.count} مرات.<div style="margin-top:8px">${list}</div><div class="mut" style="margin-top:8px">هذه النسخة تحلل المشكلات من سجل الإجراءات، وسنوسعها لاحقًا لتقرأ تفاصيل الجاهزية والتشغيل بصورة أعمق.</div>`);return}
if(t.includes('اجراء')||t.includes('متابعه')||t.includes('مفتوح')){let rows=assistantOpenActions();if(!rows.length){assistantAdd('assistant','لا توجد إجراءات مفتوحة حاليًا ✅');return}let by={};for(let x of rows)by[x.action_type]=(by[x.action_type]||0)+1;let types=Object.entries(by).map(([k,v])=>`${assistantEscText(k)}: ${v}`).join(' | '),old=rows[0];assistantAdd('assistant',`عندك <b>${rows.length}</b> إجراء مفتوح حاليًا.<div style="margin-top:7px">${types}</div>${old?`<div class="mut" style="margin-top:8px">أقدم إجراء: ${assistantEscText(old.subject)} — ${old.request_date}</div>`:''}`);return}
assistantAdd('assistant','أقدر حاليًا أساعدك في: <b>المبيعات والتارقت</b>، <b>النواقص المتكررة</b>، <b>المشكلات المسجلة</b>، و<b>الإجراءات المفتوحة</b>. وتقدر تقول مثلًا: «صدر لي مبيعات أغسطس مع التارقت Excel».')
}catch(e){assistantAdd('assistant',`<span class="re">تعذر تنفيذ الطلب: ${assistantEscText(e.message)}</span>`)}}
'''

anchor_js='function actionDisplayStatus(x)'
assert anchor_js in s, 'actionDisplayStatus anchor not found'
s=s.replace(anchor_js,assistant_js+anchor_js,1)

p.write_text(s,encoding='utf-8')
