from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
old="function assistantParseRosterInstruction(text,active,ds){let t=assistantRosterTextNorm(text),entries={},summary=[],weekRules=new Map(),dayRules=[],hasRules=false;let defaultStatus='';let dm=t.match(/(?:البقيه|الباقي|الباقين|الكل|الجميع)(?:\\s+كلهم)?\\s+(صباح(?:ي)?|مساء(?:ي)?)/);if(dm){defaultStatus=dm[1].startsWith('صباح')?'Morning':'Evening';hasRules=true;summary.push(`${dm[0].includes('البقي')||dm[0].includes('الباق')?'البقية':'الجميع'} ${defaultStatus}`)}let found=assistantRosterEmployeeMentions(t,active),mentions=found.mentions;for(let mi=0;mi<mentions.length;mi++){let m=mentions[mi],end=mi+1<mentions.length?mentions[mi+1].start:t.length,seg=t.slice(m.end,end),restAt=seg.search(/\\b(?:البقيه|الباقي|الباقين|الكل|الجميع)\\b/);if(restAt>=0)seg=seg.slice(0,restAt);let firstDay=seg.length;for(let day of ASSISTANT_ROSTER_DAYS)for(let a of day.aliases){let at=seg.indexOf(a);if(at>=0&&at<firstDay)firstDay=at}let lead=seg.slice(0,firstDay),week=assistantRosterShiftFromText(lead);if(['Morning','Evening'].includes(week)){weekRules.set(m.emp.id,week);hasRules=true;summary.push(`${m.emp.full_name}: ${week}`)}for(let day of ASSISTANT_ROSTER_DAYS){let best=-1,bestAlias='';for(let a of day.aliases){let at=seg.indexOf(a);if(at>=0&&(best<0||at<best)){best=at;bestAlias=a}}if(best<0)continue;let after=seg.slice(best+bestAlias.length,Math.min(seg.length,best+bestAlias.length+18)),st=assistantRosterShiftFromText(after)||'D/O';dayRules.push({emp:m.emp,day,status:st});hasRules=true;summary.push(`${m.emp.full_name}: ${day.label} ${st}`)}}if(defaultStatus)active.forEach(e=>ds.forEach(d=>entries[e.id+'|'+d]=defaultStatus));for(let [id,st] of weekRules){ds.forEach(d=>entries[id+'|'+d]=st)}for(let r of dayRules)entries[r.emp.id+'|'+ds[r.day.i]]=r.status;let assumptions=mentions.filter(x=>x.assumed).map(x=>`اعتبرت «${x.alias}» = ${x.emp.full_name} لأنه مدير المعرض`);return{hasRules,entries,summary:[...new Set(summary)],ambiguities:found.ambiguities,assumptions}}"
new="function assistantParseRosterInstruction(text,active,ds){let t=assistantRosterTextNorm(text),entries={},summary=[],weekRules=new Map(),dayRules=[],excluded=new Set(),hasRules=false;let defaultStatus='';let dm=t.match(/(?:البقيه|الباقي|الباقين|الكل|الجميع)(?:\\s+كلهم)?\\s+(صباح(?:ي)?|مساء(?:ي)?)/);if(dm){defaultStatus=dm[1].startsWith('صباح')?'Morning':'Evening';hasRules=true;summary.push(`${dm[0].includes('البقي')||dm[0].includes('الباق')?'البقية':'الجميع'} ${defaultStatus}`)}let found=assistantRosterEmployeeMentions(t,active),mentions=found.mentions;for(let mi=0;mi<mentions.length;mi++){let m=mentions[mi],end=mi+1<mentions.length?mentions[mi+1].start:t.length,seg=t.slice(m.end,end),before=t.slice(Math.max(0,m.start-18),m.start),restAt=seg.search(/\\b(?:البقيه|الباقي|الباقين|الكل|الجميع)\\b/);if(restAt>=0)seg=seg.slice(0,restAt);let exclusionCtx=(before+' '+seg.slice(0,22));if(/(?:الغي|الغاء|احذف|شيل|استبعد|لا تضيف|لا تحط|مو موجود|غير موجود)/.test(exclusionCtx)){excluded.add(m.emp.id);hasRules=true;summary.push(`استبعاد ${m.emp.full_name} من الخطة`);continue}let firstDay=seg.length;for(let day of ASSISTANT_ROSTER_DAYS)for(let a of day.aliases){let at=seg.indexOf(a);if(at>=0&&at<firstDay)firstDay=at}let lead=seg.slice(0,firstDay),week=assistantRosterShiftFromText(lead);if(['Morning','Evening'].includes(week)){weekRules.set(m.emp.id,week);hasRules=true;summary.push(`${m.emp.full_name}: ${week}`)}for(let day of ASSISTANT_ROSTER_DAYS){let best=-1,bestAlias='';for(let a of day.aliases){let at=seg.indexOf(a);if(at>=0&&(best<0||at<best)){best=at;bestAlias=a}}if(best<0)continue;let after=seg.slice(best+bestAlias.length,Math.min(seg.length,best+bestAlias.length+18)),st=assistantRosterShiftFromText(after)||'D/O';dayRules.push({emp:m.emp,day,status:st});hasRules=true;summary.push(`${m.emp.full_name}: ${day.label} ${st}`)}}if(defaultStatus)active.filter(e=>!excluded.has(e.id)).forEach(e=>ds.forEach(d=>entries[e.id+'|'+d]=defaultStatus));for(let [id,st] of weekRules){if(!excluded.has(id))ds.forEach(d=>entries[id+'|'+d]=st)}for(let r of dayRules)if(!excluded.has(r.emp.id))entries[r.emp.id+'|'+ds[r.day.i]]=r.status;let assumptions=mentions.filter(x=>x.assumed&&!excluded.has(x.emp.id)).map(x=>`اعتبرت «${x.alias}» = ${x.emp.full_name} لأنه مدير المعرض`);return{hasRules,entries,excluded:[...excluded],summary:[...new Set(summary)],ambiguities:found.ambiguities,assumptions}}"
if old not in s:
    raise SystemExit('target parse function not found')
s=s.replace(old,new)
old2="assistantRosterDraft={week_start:ws,week_end:ds[6],dates:ds,employees:active,entries,source_week:source,source_used:sourceUsed,exceptional,command_summary:commandSummary,command_ambiguities:parsed.ambiguities};assistantRenderRosterDraft()"
new2="let draftEmployees=active.filter(e=>!(parsed.excluded||[]).includes(e.id));assistantRosterDraft={week_start:ws,week_end:ds[6],dates:ds,employees:draftEmployees,entries,source_week:source,source_used:sourceUsed,exceptional,command_summary:commandSummary,command_ambiguities:parsed.ambiguities};assistantRenderRosterDraft()"
if old2 not in s:
    raise SystemExit('draft assignment target not found')
s=s.replace(old2,new2)
s=s.replace('<!-- pages-publish: assistant-v03-smart-roster-2026-09-09 -->','<!-- pages-publish: assistant-v04-roster-exclusions-2026-09-09 -->')
p.write_text(s,encoding='utf-8')
print('patched roster exclusions v0.4')
