from pathlib import Path
import re
p=Path('index.html')
s=p.read_text(encoding='utf-8')
s=re.sub(r'<!-- pages-publish:[^>]+-->', '<!-- pages-publish: accessories-final-simple-2026-08-25 -->', s, count=1)
ui='''<div id="shortAccBox" class="hidden"><div class="notice ok"><b>الإكسسوارات والجوارب</b><div style="margin-top:5px">اختر التصنيف الثابت، ثم اكتب نوع الصنف والكمية المطلوبة والفرص الضائعة فقط.</div></div><div class="title" style="margin-top:14px">التصنيف</div><div id="accItemChoices" class="actions fixedChoices" style="justify-content:flex-start;flex-wrap:wrap"></div><div id="accSummary" class="notice" style="margin-top:14px">اختر التصنيف.</div><div id="accSelected" class="task hidden"><div class="field"><label>نوع الصنف</label><input id="accItemType" placeholder="اكتب نوع الصنف المطلوب"></div><div class="fields" style="margin-top:10px"><div class="field"><label>الكمية المطلوبة</label><input id="accRequested" inputmode="numeric" value="0"></div><div class="field"><label>الفرص الضائعة</label><input id="accLost" inputmode="numeric" value="0"></div></div><div class="actions" style="justify-content:flex-start"><button class="btn" onclick="addAccDraft()">إضافة للنواقص</button></div></div><div class="title" style="margin-top:18px">طلب الإكسسوارات والجوارب الحالي</div><div id="accDraftList"><p class="mut">لم تتم إضافة أصناف بعد.</p></div><div class="actions"><span></span><button class="btn gold" onclick="saveAccShortages()">حفظ نواقص الإكسسوارات والجوارب</button></div></div><div class="card wide"><div class="title">السجل</div>'''
s,n=re.subn(r'<div id="shortAccBox" class="hidden">.*?</div><div class="card wide"><div class="title">السجل</div>',ui,s,count=1,flags=re.S); assert n==1
s=s.replace('accItem="",accSocksType="",accDraft=[]','accCategory="",accDraft=[]',1)
s=s.replace('accItem="";accSocksType="";accDraft=[];','accCategory="";accDraft=[];',1)
s=s.replace("if(isAcc){accItem='';accSocksType='';$('accSelected').classList.add('hidden');renderAccControls();renderAccDraft()}","if(isAcc){accCategory='';$('accSelected').classList.add('hidden');renderAccControls();renderAccDraft()}",1)
funcs="""function accItems(){return ['جوارب','أقلام','عطور','كبكات','سبح']}function renderAccControls(){$('accItemChoices').innerHTML=accItems().map(v=>`<button class=\"mini ${accCategory===v?'on':''}\" onclick=\"selectAccItem('${v}',this)\">${esc(v)}</button>`).join('');updateAccSummary()}function selectAccItem(v,b){accCategory=v;renderAccControls()}function updateAccSummary(){let ready=!!accCategory;$('accSummary').innerHTML=ready?`المحدد: <b>${esc(accCategory)}</b>`:'اختر التصنيف.';$('accSelected').classList.toggle('hidden',!ready);if(ready){$('accItemType').value='';$('accRequested').value='0';$('accLost').value='0'}}function addAccDraft(){try{if(!accCategory)throw Error('اختر التصنيف');let t=$('accItemType').value.trim();if(!t)throw Error('اكتب نوع الصنف');let label=`${accCategory} — ${t}`,section=$('shortSection').value,key=label.trim().toLowerCase(),dup=shortagesData.find(q=>q.section_id===section&&String(q.size||'').trim().toLowerCase()===key&&q.shortage_status==='تم الطلب'&&(!q.action_id||app.actions.find(z=>z.id===q.action_id)?.action_status!=='مغلق'));if(dup)throw Error(`هذا الصنف له طلب تغذية قائم بالفعل منذ ${dup.ordered_date||'—'}`);if(accDraft.some(x=>x.label.trim().toLowerCase()===key))throw Error('هذا الصنف مضاف بالفعل');let requested=Number($('accRequested').value||0),lost=Number($('accLost').value||0);if([requested,lost].some(x=>Number.isNaN(x)||x<0))throw Error('أدخل الكمية والفرص بشكل صحيح');accDraft.push({label,requested_qty:requested,lost_opportunities:lost});renderAccDraft();$('accItemType').value='';$('accRequested').value='0';$('accLost').value='0'}catch(e){alert(e.message)}}function removeAccDraft(i){accDraft.splice(i,1);renderAccDraft()}function renderAccDraft(){$('accDraftList').innerHTML=accDraft.length?accDraft.map((x,i)=>`<div class=\"task\"><b>${esc(x.label)}</b><div class=\"mut\" style=\"margin-top:6px\">الكمية المطلوبة: ${x.requested_qty} | الفرص الضائعة: ${x.lost_opportunities}</div><div style=\"margin-top:8px\"><button class=\"mini\" style=\"color:#c83b3b;border-color:#efb4b4\" onclick=\"removeAccDraft(${i})\">حذف</button></div></div>`).join(''):'<p class=\"mut\">لم تتم إضافة أصناف بعد.</p>'}"""
s,n=re.subn(r'function accItems\(\)\{.*?\}function addShortRow\(\)',funcs+'function addShortRow()',s,count=1,flags=re.S); assert n==1
s=s.replace('rows:accDraft.map(x=>({size:x.label,current_qty:x.current_qty,requested_qty:x.requested_qty,lost_opportunities:x.lost_opportunities}))','rows:accDraft.map(x=>({size:x.label,current_qty:0,requested_qty:x.requested_qty,lost_opportunities:x.lost_opportunities}))',1)
s=s.replace("accDraft=[];accItem='';accSocksType='';shortagesData=await api('shortages')","accDraft=[];accCategory='';shortagesData=await api('shortages')",1)
p.write_text(s,encoding='utf-8')