from pathlib import Path
import re
# trigger apply: 2026-08-24

p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'id="shortRethobeBox"' in s:
    raise SystemExit(0)

# 1) Add Rethobe smart UI after Zakhrafat.
needle='<button class="btn gold" onclick="saveZakhrafatShortages()">حفظ نواقص الزخرفات</button></div></div></div><div class="card wide"><div class="title">السجل</div>'
box='''<button class="btn gold" onclick="saveZakhrafatShortages()">حفظ نواقص الزخرفات</button></div></div><div id="shortRethobeBox" class="hidden"><div class="notice ok"><b>البحث الذكي — ري ثوب</b><div style="margin-top:5px">مرتبط بورقة Excel: Rethobe. ابحث بالمقاس فقط، ثم أدخل رقم الموديل يدويًا.</div></div><div class="field"><label>ابحث عن المقاس</label><input id="rethobeSearch" oninput="renderRethobeResults()" placeholder="مثال: 54M"></div><div id="rethobeResults" style="margin-top:10px"></div><div id="rethobeSelected" class="task hidden"><b id="rethobeChosenLabel">—</b><div class="mut" id="rethobeChosenMeta" style="margin-top:5px">ري ثوب</div><div class="field" style="margin-top:10px"><label>رقم الموديل</label><input id="rethobeStyle" inputmode="numeric" placeholder="اكتب رقم الموديل الحالي"></div><div class="fields" style="margin-top:10px"><div class="field"><label>الموجود حاليًا</label><input id="rethobeCurrent" inputmode="numeric" value="0"></div><div class="field"><label>المطلوب للتغذية</label><input id="rethobeRequested" inputmode="numeric" value="0"></div><div class="field"><label>الفرص الضائعة</label><input id="rethobeLost" inputmode="numeric" value="0"></div></div><div class="actions" style="justify-content:flex-start"><button class="btn" onclick="addRethobeDraft()">إضافة للنواقص</button></div></div><div class="title" style="margin-top:18px">طلب ري ثوب الحالي</div><div id="rethobeDraftList"><p class="mut">لم تتم إضافة أصناف بعد.</p></div><div class="actions"><span></span><button class="btn gold" onclick="saveRethobeShortages()">حفظ نواقص ري ثوب</button></div></div></div><div class="card wide"><div class="title">السجل</div>'''
assert needle in s, 'Zakhrafat box ending not found'
s=s.replace(needle,box,1)

# 2) State and catalog. Rethobe size matrix is identical to Zakhrafat in the company workbook.
old_state='zakhrafatSelectedItem=null,zakhrafatDraft=[];'
new_state='zakhrafatSelectedItem=null,zakhrafatDraft=[],rethobeSelectedItem=null,rethobeDraft=[];'
assert old_state in s, 'Zakhrafat state marker not found'
s=s.replace(old_state,new_state,1)

marker='ZAKHRAFAT_CATALOG.forEach((x,i)=>x.i=i);'
cat="""ZAKHRAFAT_CATALOG.forEach((x,i)=>x.i=i);const RETHOBE_AR=ZAKHRAFAT_AR;const RETHOBE_CATALOG=Object.entries(ZAKHRAFAT_GROUPS).flatMap(([generation,sizes])=>sizes.map(size=>({generation,size,label:size,search:`${size} ${generation} ${RETHOBE_AR[generation]} ري ثوب rethobe`})));RETHOBE_CATALOG.forEach((x,i)=>x.i=i);"""
assert marker in s, 'Zakhrafat catalog marker not found'
s=s.replace(marker,cat,1)

# 3) Reset Rethobe draft whenever shortages page opens.
old_reset="zakhrafatSelectedItem=null;zakhrafatDraft=[];$('shortSection')"
new_reset="zakhrafatSelectedItem=null;zakhrafatDraft=[];rethobeSelectedItem=null;rethobeDraft=[];$('shortSection')"
assert old_reset in s, 'Zakhrafat reset marker not found'
s=s.replace(old_reset,new_reset,1)

# 4) Route Rethobe to its own smart box.
pat=r"function shortSectionChanged\(\)\{.*?\}function renderFakherResults"
new_route=r'''function shortSectionChanged(){let sec=app.sections.find(s=>s.id===$('shortSection').value),isFakher=sec?.name==='الفاخر',isBusiness=sec?.name==='الأعمال',isSchool=sec?.name==='الحركات',isClassic=sec?.name==='الكلاسيك',isZakhrafat=sec?.name==='الزخرفات',isRethobe=sec?.name==='ري ثوب',isSmart=isFakher||isBusiness||isSchool||isClassic||isZakhrafat||isRethobe;$('shortLegacyBox').classList.toggle('hidden',isSmart);$('shortFakherBox').classList.toggle('hidden',!isFakher);$('shortBusinessBox').classList.toggle('hidden',!isBusiness);$('shortSchoolBox').classList.toggle('hidden',!isSchool);$('shortClassicBox').classList.toggle('hidden',!isClassic);$('shortZakhrafatBox').classList.toggle('hidden',!isZakhrafat);$('shortRethobeBox').classList.toggle('hidden',!isRethobe);if(isFakher){fakherSelectedItem=null;$('fakherSelected').classList.add('hidden');$('fakherSearch').value='';$('fakherResults').innerHTML='<p class="mut">ابدأ بالكتابة للبحث في مقاسات وألوان الفاخر.</p>';renderFakherDraft()}if(isBusiness){businessSelectedItem=null;$('businessSelected').classList.add('hidden');$('businessSearch').value='';$('businessResults').innerHTML='<p class="mut">ابدأ بالكتابة للبحث في مقاسات وألوان الأعمال.</p>';renderBusinessDraft()}if(isSchool){schoolSelectedItem=null;$('schoolSelected').classList.add('hidden');$('schoolSearch').value='';$('schoolResults').innerHTML='<p class="mut">ابدأ بالكتابة للبحث في مقاسات وفئات الحركات.</p>';renderSchoolDraft()}if(isClassic){classicSelectedItem=null;$('classicSelected').classList.add('hidden');$('classicSearch').value='';$('classicResults').innerHTML='<p class="mut">ابدأ بالكتابة للبحث في مقاس أو نوع أو لون الكلاسيك.</p>';renderClassicDraft()}if(isZakhrafat){zakhrafatSelectedItem=null;$('zakhrafatSelected').classList.add('hidden');$('zakhrafatSearch').value='';$('zakhrafatResults').innerHTML='<p class="mut">ابدأ بالكتابة للبحث في مقاسات الزخرفات.</p>';renderZakhrafatDraft()}if(isRethobe){rethobeSelectedItem=null;$('rethobeSelected').classList.add('hidden');$('rethobeSearch').value='';$('rethobeResults').innerHTML='<p class="mut">ابدأ بالكتابة للبحث في مقاسات ري ثوب.</p>';renderRethobeDraft()}}function renderFakherResults'''
s,n=re.subn(pat,new_route,s,count=1,flags=re.S)
assert n==1, 'shortSectionChanged block not found'

# 5) Rethobe search / draft functions: size fixed, style entered manually.
funcs=r'''function renderRethobeResults(){let q=$('rethobeSearch').value.trim().toLowerCase();if(!q){$('rethobeResults').innerHTML='<p class="mut">ابدأ بالكتابة للبحث في مقاسات ري ثوب.</p>';return}let rows=RETHOBE_CATALOG.filter(x=>x.search.toLowerCase().includes(q)).slice(0,24);$('rethobeResults').innerHTML=rows.length?'<div class="actions" style="justify-content:flex-start;flex-wrap:wrap">'+rows.map(x=>`<button class="mini" onclick="selectRethobeItem(${x.i})">${esc(x.size)}</button>`).join('')+'</div>':'<div class="notice">لا يوجد مقاس مطابق في نموذج ري ثوب.</div>'}function selectRethobeItem(i){let x=RETHOBE_CATALOG[i];if(!x)return;rethobeSelectedItem=x;$('rethobeChosenLabel').textContent=x.size;$('rethobeChosenMeta').textContent=`ري ثوب • ${RETHOBE_AR[x.generation]} • ${x.generation}`;$('rethobeStyle').value='';$('rethobeCurrent').value='0';$('rethobeRequested').value='0';$('rethobeLost').value='0';$('rethobeSelected').classList.remove('hidden')}function addRethobeDraft(){try{if(!rethobeSelectedItem)throw Error('اختر المقاس أولًا');let style=$('rethobeStyle').value.trim();if(!style)throw Error('أدخل رقم الموديل');let label=`${rethobeSelectedItem.size} — موديل ${style}`,section=$('shortSection').value,key=label.trim().toLowerCase(),dup=shortagesData.find(q=>{if(q.section_id!==section||String(q.size||'').trim().toLowerCase()!==key||q.shortage_status!=='تم الطلب')return false;let a=q.action_id?app.actions.find(z=>z.id===q.action_id):null;return !a||a.action_status!=='مغلق'});if(dup)throw Error(`هذا الصنف له طلب تغذية قائم بالفعل منذ ${dup.ordered_date||'—'}`);if(rethobeDraft.some(x=>x.label===label))throw Error('هذا الصنف مضاف بالفعل في الطلب الحالي');let current=Number($('rethobeCurrent').value||0),requested=Number($('rethobeRequested').value||0),lost=Number($('rethobeLost').value||0);if([current,requested,lost].some(x=>Number.isNaN(x)||x<0))throw Error('أدخل الكميات بشكل صحيح');rethobeDraft.push({label,size:rethobeSelectedItem.size,style,generation:rethobeSelectedItem.generation,current_qty:current,requested_qty:requested,lost_opportunities:lost});renderRethobeDraft();rethobeSelectedItem=null;$('rethobeSelected').classList.add('hidden');$('rethobeSearch').value='';$('rethobeResults').innerHTML='<p class="mut">تمت الإضافة. ابحث عن مقاس آخر أو احفظ الطلب.</p>'}catch(e){alert(e.message)}}function removeRethobeDraft(i){rethobeDraft.splice(i,1);renderRethobeDraft()}function renderRethobeDraft(){$('rethobeDraftList').innerHTML=rethobeDraft.length?rethobeDraft.map((x,i)=>`<div class="task"><b>${esc(x.label)}</b><div class="mut" style="margin-top:6px">${esc(RETHOBE_AR[x.generation]||x.generation)} | الموجود: ${x.current_qty} | المطلوب: ${x.requested_qty} | الفرص الضائعة: ${x.lost_opportunities}</div><div style="margin-top:8px"><button class="mini" style="color:#c83b3b;border-color:#efb4b4" onclick="removeRethobeDraft(${i})">حذف</button></div></div>`).join(''):'<p class="mut">لم تتم إضافة أصناف بعد.</p>'}'''
assert 'function addShortRow()' in s, 'addShortRow marker not found'
s=s.replace('function addShortRow()',funcs+'function addShortRow()',1)

# 6) Save Rethobe through the existing shortages lifecycle.
save=r'''async function saveRethobeShortages(){try{let section=$('shortSection').value,sec=app.sections.find(s=>s.id===section);if(sec?.name!=='ري ثوب')throw Error('اختر قسم ري ثوب');if(!rethobeDraft.length)throw Error('أضف صنفًا واحدًا على الأقل');for(const row of rethobeDraft){let key=row.label.trim().toLowerCase(),dup=shortagesData.find(q=>{if(q.section_id!==section||String(q.size||'').trim().toLowerCase()!==key||q.shortage_status!=='تم الطلب')return false;let a=q.action_id?app.actions.find(z=>z.id===q.action_id):null;return !a||a.action_status!=='مغلق'});if(dup)throw Error(`يوجد طلب قائم للصنف ${row.label} منذ ${dup.ordered_date||'—'}`)}await api('shortage-save',{method:'POST',body:{section_id:section,reporter_employee_id:$('shortReporter').value,rows:rethobeDraft.map(x=>({size:x.label,current_qty:x.current_qty,requested_qty:x.requested_qty,lost_opportunities:x.lost_opportunities}))}});rethobeDraft=[];rethobeSelectedItem=null;shortagesData=await api('shortages');renderRethobeDraft();renderShortages();alert('تم حفظ نواقص ري ثوب')}catch(e){alert(e.message)}}'''
assert 'function setShortageFilter(id)' in s, 'Shortage filter marker not found'
s=s.replace('function setShortageFilter(id)',save+'function setShortageFilter(id)',1)

# 7) Publication marker.
s=re.sub(r'<!-- pages-publish: [^>]+ -->','<!-- pages-publish: rethobe-manual-style-2026-08-24 -->',s,count=1)
p.write_text(s,encoding='utf-8')
