from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

replacement=r'''function renderActions(){let t=$('filterType').value,s=$('filterStatus').value,a=app.actions.filter(x=>(!t||x.action_type===t)&&(!s||x.action_status===s));$('actionList').innerHTML=a.map(x=>`<div class="task"><b>${esc(x.action_type)} — ${esc(x.subject)}</b><p>${esc(x.description||'')}</p><div class="mut">${x.request_date} | ${esc(x.raised_to||'')} | ${x.action_status}</div><p>${esc(x.resolution_result||'')}</p>${x.action_status!=='مغلق'?`<div class="actions" style="justify-content:flex-start"><button class="mini" onclick="escalateAction('${x.id}')">تصعيد</button><button class="mini" style="color:#166534;border-color:#86c99a;font-weight:700" onclick="closeAction('${x.id}')">إغلاق الطلب</button></div>`:'<div class="notice ok">الطلب مغلق</div>'}</div>`).join('')||'<p class="mut">لا توجد إجراءات.</p>'}function actionById(id){return app.actions.find(x=>x.id===id)}function actionUpdateBody(x,extra={}){return{id:x.id,action_type:x.action_type,subject:x.subject,description:x.description||'',request_date:x.request_date||app.date,raised_to:x.raised_to||'',action_status:x.action_status||'جديد',last_update:x.last_update||app.date,resolution_result:x.resolution_result||'',...extra}}async function escalateAction(id){try{let x=actionById(id);if(!x)throw Error('الإجراء غير موجود');let to=prompt('الجهة المرفوع لها:',x.raised_to||'');if(to===null)return;to=to.trim();if(!to)throw Error('حدد الجهة المرفوع لها');await api('action-save',{method:'POST',body:actionUpdateBody(x,{raised_to:to,action_status:'تم الرفع',last_update:app.calendarDate||app.date})});await refresh();openActions();alert('تم تصعيد الطلب')}catch(e){alert(e.message)}}async function closeAction(id){try{let x=actionById(id);if(!x)throw Error('الإجراء غير موجود');let result=prompt('نتيجة المعالجة قبل إغلاق الطلب:',x.resolution_result||'');if(result===null)return;result=result.trim();if(!result)throw Error('نتيجة المعالجة مطلوبة لإغلاق الطلب');await api('action-save',{method:'POST',body:actionUpdateBody(x,{action_status:'مغلق',resolution_result:result,last_update:app.calendarDate||app.date})});await refresh();openActions();alert('تم إغلاق الطلب')}catch(e){alert(e.message)}}async function saveAction'''

s,n=re.subn(r'function renderActions\(\)\{.*?\}async function saveAction',replacement,s,count=1,flags=re.S)
assert n==1, 'renderActions block not found'
p.write_text(s,encoding='utf-8')
